### PR TITLE
Update batman.html

### PR DESCRIPTION
**Pull request by TechyPig99**

### CODE REVIEW

**Comment by TechyPig99** [comment]
Coding i'll leave a comment when done

**Comment by BlueMicrowave** [comment]
balls.

**Comment by TechyPig99** [comment]
Done

**Comment by BlueMicrowave** [comment]
i was gonna reorganize the code but i guess if it works thats fine also if you could add tetris.html ?

**Comment by BlueMicrowave** [comment]
nvm fuck that shit

**Pull request merged**
